title: "Houssam Zouhri"
description: "Personal portfolio of Houssam Zouhri, Data Scientist & PhD researcher in Cybersecurity"
author: "Houssam Zouhri"
url: "https://houssam-zouhri.github.io" 
baseurl: "" 

# Social Media links
social_links:
  github: "https://github.com/Houssam-Zouhri"
  linkedin: "https://linkedin.com/in/houssamzouhri"
  email: "mailto:houssam.zouhri@um6p.ma"

# Logo and Branding
logo: "/assets/images/logo.jpeg"

# Theme 
theme: "minima"

# Customize the appearance
main_header:
  image: "/assets/images/logo.jpeg" # Banner image displayed in the header section
  image_position: "left"  # Can be left, center, or right

# Navigation settings
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Projects"
    url: "/projects/"
  - title: "Contact"
    url: "/contact/"

# Enable social sharing
social_share: true

# Enable disqus for comments (Optional)
comments:
  provider: "disqus"
  shortname: "your-disqus-shortname" # Replace with your Disqus shortname if you want comments

# SEO and Sitemap settings
seo:
  title: "Houssam Zouhri Portfolio"
  description: "Explore the personal portfolio of Houssam Zouhri, showcasing projects in data science and cybersecurity"
  keywords: "Data Science, Machine Learning, Cybersecurity, PhD, Portfolio"

# Analytics (Optional)
google_analytics: "UA-XXXXXXX-X" # Replace with your Google Analytics tracking ID if you want to track visitors

# Enable RSS feed
plugins:
  - jekyll-feed

